server:
  port: 33003

eureka:
  client:
    serviceUrl:
      defaultZone: http://61.28.227.69:10002/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  #file: userservice3.log
  file: /var/kido/logs/userservice3.log